rules:
  # ============================================
  # Mass Assignment Detection Rules
  # ============================================
  - id: mass-assignment-prisma-update
    patterns:
      - pattern:  "$PRISMA.$MODEL.update({ data: $DATA, ... })"
      - metavariable-pattern:
          metavariable: $DATA
          pattern: req.body
    message: "Potential mass assignment vulnerability: Using req.body directly in Prisma update. Manually destructure inputs to prevent mass assignment."
    severity: WARNING
    languages: [typescript, javascript]

  - id: mass-assignment-general-update
    patterns:
      - pattern: $OBJ.update($BODY)
      - metavariable-pattern:
          metavariable: $BODY
          pattern: req.body
    message: "Potential mass assignment vulnerability: Passing req.body directly to update method. Use manual destructuring instead."
    severity: WARNING
    languages: [typescript, javascript]

  - id: mass-assignment-prisma-update-spread
    patterns:
      - pattern: "$PRISMA.$MODEL.update({ data: { ...$SPREAD }, ... })"
      - metavariable-pattern:
          metavariable: $SPREAD
          pattern: req.body
    message: "Potential mass assignment vulnerability: Using spread operator with req.body in Prisma update. Manually destructure specific fields instead."
    severity: WARNING
    languages: [typescript, javascript]

  - id: mass-assignment-prisma-create
    patterns:
      - pattern: "$PRISMA.$MODEL.create({ data: $DATA, ... })"
      - metavariable-pattern:
          metavariable: $DATA
          pattern: req.body
    message: "Potential mass assignment vulnerability: Using req.body directly in Prisma create. Manually destructure inputs to prevent mass assignment."
    severity: WARNING
    languages: [typescript, javascript]

  - id: mass-assignment-repository-update
    patterns:
      - pattern: "$REPO.update($ID, $DATA)"
      - metavariable-pattern:
          metavariable: $DATA
          pattern: req.body
    message: "Potential mass assignment vulnerability: Passing req.body directly to repository update method. Manually destructure inputs (e.g., { name: req.body.name }) instead."
    severity: WARNING
    languages: [typescript, javascript]

  - id: mass-assignment-service-update
    patterns:
      - pattern: "$SERVICE.update($ID, $DATA)"
      - metavariable-pattern:
          metavariable: $DATA
          pattern: req.body
    message: "Potential mass assignment vulnerability: Passing req.body directly to service update method. Manually destructure inputs instead."
    severity: WARNING
    languages: [typescript, javascript]

  # ============================================
  # SQL Injection Detection Rules
  # ============================================
  - id: sql-injection-raw-query-string-concat
    patterns:
      - pattern: |
          $QUERY = $SQL + $VAR
      - pattern: |
          $QUERY = $VAR + $SQL
      - pattern: |
          $QUERY = "`...${$VAR}...`"
      - metavariable-pattern:
          metavariable: $QUERY
          pattern-either:
            - pattern: prisma.$queryRaw(...)
            - pattern: prisma.$executeRaw(...)
            - pattern: $DB.query(...)
            - pattern: $DB.execute(...)
            - pattern: $POOL.query(...)
            - pattern: $CLIENT.query(...)
    message: "SQL Injection vulnerability: String concatenation in SQL query detected. Use parameterized queries with $1, $2 syntax (pg) or ORM binding instead of string concatenation."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-injection-template-literal-raw
    patterns:
      - pattern: |
          prisma.$queryRaw`SELECT * FROM $TABLE WHERE id = ${$VAR}`
      - pattern: |
          prisma.$executeRaw`UPDATE $TABLE SET name = ${$VAR}`
      - pattern: |
          $DB.query("`SELECT * FROM $TABLE WHERE id = ${$VAR}`")
      - pattern: |
          $POOL.query("`SELECT * FROM $TABLE WHERE id = ${$VAR}`")
    message: "SQL Injection vulnerability: Template literal interpolation in raw SQL query. Use Prisma.$queryRaw with Prisma.sql template tag and parameterized queries ($1, $2) instead."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-injection-prisma-raw-without-sql-tag
    patterns:
      - pattern: |
          prisma.$queryRaw($QUERY)
      - pattern-not-inside: |
          Prisma.sql`...`
      - metavariable-pattern:
          metavariable: $QUERY
          pattern-either:
            - pattern: "`...${...}...`"
            - pattern: $STR + $VAR
            - pattern: $VAR + $STR
    message: "SQL Injection vulnerability: Raw SQL query without Prisma.sql template tag. Use Prisma.sql template tag for safe parameterized queries."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-injection-pg-query-string-concat
    patterns:
      - pattern: |
          $CLIENT.query($QUERY, ...)
      - metavariable-pattern:
          metavariable: $QUERY
          pattern-either:
            - pattern: "`...${...}...`"
            - pattern: $STR + $VAR
            - pattern: $VAR + $STR
    message: "SQL Injection vulnerability: String concatenation in pg query. Use parameterized queries with $1, $2, $3 placeholders instead (e.g., query('SELECT * FROM users WHERE id = $1', [userId]))."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-injection-pg-query-missing-params
    patterns:
      - pattern: |
          $CLIENT.query($QUERY)
      - pattern-not: |
          $CLIENT.query($QUERY, [$PARAMS])
      - metavariable-pattern:
          metavariable: $QUERY
          pattern-either:
            - pattern: "`...${...}...`"
            - pattern: $STR + $VAR
    message: "SQL Injection vulnerability: pg query with string interpolation but no parameter array. Use parameterized queries: query('SELECT * FROM users WHERE id = $1', [userId])."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-injection-raw-sql-with-vars
    patterns:
      - pattern: |
          $DB.query($SQL, $VARS)
      - metavariable-pattern:
          metavariable: $SQL
          pattern-either:
            - pattern: "`...${...}...`"
            - pattern: $STR + $VAR
            - pattern: $VAR + $STR
    message: "SQL Injection vulnerability: SQL query string contains variable interpolation. Use parameterized queries with placeholders ($1, $2) and pass values in parameter array."
    severity: ERROR
    languages: [typescript, javascript]

  # ============================================
  # Database Constraints - Negative Quantity Prevention
  # Note: SQL and Prisma language rules are handled by check-db-constraints.js script
  # Semgrep doesn't support SQL or Prisma languages, so these checks are done via custom script
  # ============================================

  - id: insecure-random-math-random
    pattern: Math.random()
    message: "Insecure random number generation: Math.random() is not cryptographically secure. Use crypto.randomBytes() for security tokens, passwords, or any security-sensitive operations."
    severity: ERROR
    languages: [typescript, javascript]

  - id: insecure-cookie-settings
    patterns:
      - pattern: res.cookie($NAME, $VALUE, $OPTIONS)
      - pattern-not-inside: |
          httpOnly: true
      - pattern-not-inside: |
          secure: true
      - pattern-not-inside: |
          sameSite: 'strict'
    message: "Insecure cookie settings: Cookies should be set with httpOnly: true, secure: true, and sameSite: 'strict' to prevent XSS and CSRF attacks. Use setAuthCookie() helper for JWT tokens."
    severity: ERROR
    languages: [typescript, javascript]

  - id: insecure-jwt-verification
    patterns:
      - pattern: jwt.verify($TOKEN, $SECRET)
      - pattern-not-inside: |
          algorithms: ['HS256']
      - pattern-not-inside: |
          algorithms: ['RS256']
    message: "Insecure JWT verification: jwt.verify() should specify algorithms explicitly (e.g., algorithms: ['HS256'] or ['RS256']) to prevent algorithm confusion attacks."
    severity: ERROR
    languages: [typescript, javascript]

  - id: manual-jwt-decoding
    pattern: Buffer.from($PAYLOAD, 'base64').toString()
    message: "Manual JWT decoding detected: Avoid manual JWT decoding. Use proper JWT verification libraries with algorithm specification to prevent security vulnerabilities."
    severity: WARNING
    languages: [typescript, javascript]

  - id: missing-ownership-check
    patterns:
      - pattern: |
          $RESOURCE = await $REPO.findById($ID)
          ...
          return $RESOURCE
      - pattern-not: |
          if ($RESOURCE.owner_id !== req.user.id) {
            ...
          }
      - pattern-not: |
          requireOwnership()
    message: "Potential authorization bypass: Returning resource data without verifying ownership (resource.owner_id === req.user.id). Ensure proper authorization checks before returning sensitive data."
    severity: ERROR
    languages: [typescript, javascript]

  - id: missing-user-filter-query
    patterns:
      - pattern: prisma.$MODEL.findMany(...)
      - pattern-not-inside: |
          where: {
            user_id: req.user.id,
            ...
          }
      - pattern-not-inside: |
          where: {
            owner_id: req.user.id,
            ...
          }
    message: "Potential data leakage: Querying user-specific data without filtering by current user. Add user_id or owner_id filter to prevent unauthorized access."
    severity: WARNING
    languages: [typescript, javascript]

  # ============================================
  # Credential Leak in Logs Prevention
  # ============================================
  - id: credential-leak-direct-logging
    patterns:
      - pattern: |
          logger.$LEVEL($MSG, { ...$DATA })
      - metavariable-pattern:
          metavariable: $DATA
          pattern-either:
            - pattern: "password: $VAL"
            - pattern: "token: $VAL"
            - pattern: "refresh_token: $VAL"
            - pattern: "access_token: $VAL"
            - pattern: "authorization: $VAL"
            - pattern: "cvv: $VAL"
            - pattern: "credit_card: $VAL"
            - pattern: "secret: $VAL"
            - pattern: "api_key: $VAL"
            - pattern: "apiKey: $VAL"
    message: "Credential leak risk: Directly logging sensitive fields (password, token, etc.) without redaction. Ensure logger is configured with redaction formatter. Use logger from utils/logger.ts which has redaction enabled."
    severity: ERROR
    languages: [typescript, javascript]

  - id: credential-leak-req-body-logging
    patterns:
      - pattern: |
          logger.$LEVEL($MSG, req.body)
      - pattern: |
          logger.$LEVEL($MSG, { body: req.body })
    message: "Credential leak risk: Logging req.body directly may expose passwords, tokens, and other sensitive data. Use logger with redaction or manually exclude sensitive fields."
    severity: ERROR
    languages: [typescript, javascript]

  - id: credential-leak-req-headers-logging
    patterns:
      - pattern: |
          logger.$LEVEL($MSG, req.headers)
      - pattern: |
          logger.$LEVEL($MSG, { headers: req.headers })
      - pattern-not-inside: |
          if ($ENV === 'development') {
            ...
          }
    message: "Credential leak risk: Logging req.headers may expose Authorization tokens. Ensure logger has redaction configured or exclude Authorization header manually."
    severity: WARNING
    languages: [typescript, javascript]

  - id: credential-leak-console-logging
    patterns:
      - pattern: |
          console.log($DATA)
      - pattern: |
          console.error($DATA)
      - pattern: |
          console.info($DATA)
      - pattern: |
          console.warn($DATA)
      - metavariable-pattern:
          metavariable: $DATA
          pattern-either:
            - pattern: req.body
            - pattern: req.headers
    message: "Credential leak risk: Using console.log/error/info/warn with sensitive data (req.body, req.headers). Use logger from utils/logger.ts instead, which has redaction configured. Never use console.* for logging in production."
    severity: ERROR
    languages: [typescript, javascript]

  - id: logger-missing-redaction
    patterns:
      - pattern: |
          winston.createLogger($CONFIG)
      - pattern-not-inside: |
          redactSensitive()
      - pattern-not-inside: |
          redact
    message: "Missing log redaction: Winston logger should include redaction formatter to mask sensitive fields (password, token, etc.) before writing to stdout or files. Add redactSensitive() formatter."
    severity: ERROR
    languages: [typescript, javascript]

  - id: console-transport-missing-redaction
    patterns:
      - pattern: |
          new winston.transports.Console({
            format: winston.format.combine(
              ...
            )
          })
      - pattern-not-inside: |
          redactSensitive()
      - pattern-not-inside: |
          redact
    message: "Missing console redaction: Console transport should include redaction formatter to prevent credential leaks in stdout. Add redactSensitive() before other formatters."
    severity: ERROR
    languages: [typescript, javascript]

  # ============================================
  # Database Schema Leak Prevention
  # ============================================
  - id: db-schema-leak-prisma-error
    patterns:
      - pattern: |
          res.status($CODE).json({
            message: $ERR.message,
            $REST
          })
      - pattern-not-inside: |
          if ($ENV === 'development' || $ENV !== 'production') {
            $BODY
          }
      - pattern-not-inside: |
          config.nodeEnv === 'development'
      - metavariable-pattern:
          metavariable: $ERR
          pattern-either:
            - pattern: prismaError
            - pattern: $PRISMA_ERROR
            - pattern: err
    message: "Database schema leak risk: Prisma/database error messages may contain table names, column names, or constraint names. Return generic error messages in production. Use error handler that sanitizes Prisma errors."
    severity: ERROR
    languages: [typescript, javascript]

  - id: db-schema-leak-error-message
    patterns:
      - pattern: |
          res.status($CODE).json({
            error: $ERR.message,
            $REST
          })
      - pattern-not-inside: |
          if ($ENV === 'development') {
            $BODY
          }
      - pattern-not-inside: |
          config.nodeEnv === 'development'
      - metavariable-pattern:
          metavariable: $ERR
          pattern-either:
            - pattern: err
            - pattern: error
            - pattern: $ERROR
    message: "Database schema leak risk: Error messages may contain database schema information (table names, column names, SQL syntax). Return generic error messages in production."
    severity: WARNING
    languages: [typescript, javascript]

  - id: db-schema-leak-prisma-meta
    patterns:
      - pattern: |
          res.status($CODE).json({
            meta: $PRISMA_ERROR.meta,
            $REST
          })
      - pattern: |
          res.status($CODE).json($PRISMA_ERROR.meta)
    message: "Database schema leak: Prisma error meta contains database schema information (table names, column names, constraints). Never expose meta field to clients."
    severity: ERROR
    languages: [typescript, javascript]

  - id: missing-global-error-handler
    patterns:
      - pattern: |
          const app = express()
          ...
      - pattern-not: |
          app.use($ERROR_HANDLER)
      - pattern-not: |
          app.use(errorHandler)
    message: "Missing global error handler: Express app should have a global error handler middleware as the last middleware to catch all errors and prevent schema leaks. Add: app.use(errorHandler);"
    severity: ERROR
    languages: [typescript, javascript]

  - id: prisma-error-not-handled
    patterns:
      - pattern: |
          try {
            ...
            await prisma.$MODEL.$METHOD(...)
            ...
          } catch ($ERR) {
            ...
            res.status($CODE).json({
              message: $ERR.message,
              ...
            })
          }
      - pattern-not-inside: |
          if ($ENV === 'development') {
            ...
            message: $ERR.message,
            ...
          }
      - pattern-not-inside: |
          config.nodeEnv === 'development'
    message: "Prisma error not sanitized: Catching Prisma errors and returning error.message directly may leak database schema. Use global error handler or sanitize Prisma errors before returning to client."
    severity: ERROR
    languages: [typescript, javascript]

  - id: sql-error-exposure
    patterns:
      - pattern: |
          res.status($CODE).json({
            message: $ERR.message,
            $REST
          })
      - pattern-not-inside: |
          if ($ENV === 'development') {
            $BODY
          }
      - metavariable-pattern:
          metavariable: $ERR
          pattern-either:
            - pattern: err
            - pattern: error
            - pattern: $ERROR
    message: "SQL error exposure risk: Error messages containing SQL syntax, table names, or column names should not be exposed to clients. Return generic error messages in production."
    severity: WARNING
    languages: [typescript, javascript]

  # ============================================
  # Dependency Vulnerability Detection
  # ============================================
  - id: outdated-react-version
    patterns:
      - pattern: |
          "react": "$VERSION"
      - metavariable-pattern:
          metavariable: $VERSION
          pattern-regex: "^(19\\.(0|1)|18\\.(0|1)|17\\.|16\\.|15\\.|14\\.|13\\.|12\\.|11\\.|10\\.|9\\.|8\\.|7\\.|6\\.|5\\.|4\\.|3\\.|2\\.|1\\.|0\\.)"
    message: "Outdated React version: React may be vulnerable to CVE-2025-66478 (React2Shell RCE). Update React to version 19.2.0, 19.3.0, 19.4.0, 20.0.0, 18.3.0, or 18.2.0 or later. Run 'npm audit fix' or update package.json."
    severity: ERROR
    languages: [json]

  - id: outdated-nextjs-version
    patterns:
      - pattern: |
          "next": "$VERSION"
      - metavariable-pattern:
          metavariable: $VERSION
          pattern-regex: "^(15\\.|14\\.|13\\.|12\\.|11\\.|10\\.|9\\.|8\\.|7\\.|6\\.|5\\.|4\\.|3\\.|2\\.|1\\.|0\\.)"
    message: "Outdated Next.js version: Next.js may contain security vulnerabilities. Update to version 16.0.10 or later. Run 'npm audit fix' or update package.json."
    severity: WARNING
    languages: [json]

  - id: vulnerable-dependency-pattern
    patterns:
      - pattern: |
          "$PKG": "$VERSION"
      - metavariable-pattern:
          metavariable: $VERSION
          pattern-either:
            - pattern: "*"
            - pattern: "latest"
            - pattern: "^0.0.0"
            - pattern: "0.0.0"
    message: "Potentially vulnerable dependency: Using wildcard (*), latest, or 0.0.0 version may include vulnerable packages. Pin to specific versions and run 'npm audit' regularly."
    severity: WARNING
    languages: [json]